python lsm_hawp_inference_acceration.py -i /root/autodl-tmp/Inpainting/DL3DV/D_fault/D_imgs_5_10/ -o /root/autodl-tmp/Inpainting/DL3DV/D_fault/D_imgs_5_10/D_pkls/
python lsm_hawp_inference_acceration.py -i /root/autodl-tmp/Inpainting/DL3DV/D_fault/D_imgs_10_20/ -o /root/autodl-tmp/Inpainting/DL3DV/D_fault/D_imgs_10_20/D_pkls/
python lsm_hawp_inference_acceration.py -i /root/autodl-tmp/Inpainting/DL3DV/D_fault/D_imgs_20_30/ -o /root/autodl-tmp/Inpainting/DL3DV/D_fault/D_imgs_20_30/D_pkls/
python lsm_hawp_inference_acceration.py -i /root/autodl-tmp/Inpainting/DL3DV/D_fault/D_imgs_30_40/ -o /root/autodl-tmp/Inpainting/DL3DV/D_fault/D_imgs_30_40/D_pkls/
python lsm_hawp_inference_acceration.py -i /root/autodl-tmp/Inpainting/DL3DV/D_fault/D_imgs_40_50/ -o /root/autodl-tmp/Inpainting/DL3DV/D_fault/D_imgs_40_50/D_pkls/
python lsm_hawp_inference_acceration.py -i /root/autodl-tmp/Inpainting/ScannetPP/S_fault/S_imgs_5_10/ -o /root/autodl-tmp/Inpainting/ScannetPP/S_fault/S_imgs_5_10/D_pkls/
python lsm_hawp_inference_acceration.py -i /root/autodl-tmp/Inpainting/ScannetPP/S_fault/S_imgs_10_20/ -o /root/autodl-tmp/Inpainting/ScannetPP/S_fault/S_imgs_10_20/D_pkls/
python lsm_hawp_inference_acceration.py -i /root/autodl-tmp/Inpainting/ScannetPP/S_fault/S_imgs_20_30/ -o /root/autodl-tmp/Inpainting/ScannetPP/S_fault/S_imgs_20_30/D_pkls/
python lsm_hawp_inference_acceration.py -i /root/autodl-tmp/Inpainting/ScannetPP/S_fault/S_imgs_30_40/ -o /root/autodl-tmp/Inpainting/ScannetPP/S_fault/S_imgs_30_40/D_pkls/
python lsm_hawp_inference_acceration.py -i /root/autodl-tmp/Inpainting/ScannetPP/S_fault/S_imgs_40_50/ -o /root/autodl-tmp/Inpainting/ScannetPP/S_fault/S_imgs_40_50/D_pkls/