pretrain_ckpt: "/root/autodl-tmp/Inpainting/Geo_inpainting/ckpt/Geo_noAlign/best.pth"
validation_path: "../filter_results/DL3DV10K_filtered_val/train_imgs_clean.txt"
valid_mask_path: "../data_list/irregular_mask_30_40.txt"
val_wireframes_list: "../filter_results/DL3DV10K_filtered_val/train_pkls_clean.txt"
AMP: True
MaP: True